### ISSUE TITLE
Side Gear Auto

### ISSUE THREAD

**Issue by OmariM** [WiredCatsRobotics2415/WiredCats2017#10]
![20170208_175259](https://cloud.githubusercontent.com/assets/6325721/22864471/20f2d09a-f120-11e6-8237-6d58457de888.jpg)

make it happen. the points are on the baseline for each peg must be the point where a line extended from the peg intersects with the baseline.

edit: get the measurements from the field drawings were released on kickoff--*NOT* the field that we replicated on the carpets

**Comment by OmariM** [comment]
@isabellapu can you post your pic here

**Comment by ZainPalanpur** [comment]
![f32bce47f9bd4a9e80d6c58c150d7e16](https://cloud.githubusercontent.com/assets/22061595/23021839/f63fcb1a-f41b-11e6-8098-6789010d3efe.jpeg)

**Comment by OmariM** [comment]
close enough
