### ISSUE TITLE
Make ReadMe Kawaii

### ISSUE THREAD

**Issue by OmariM** [WiredCatsRobotics2415/WiredCats2017#7]
Things it needs to include:
- how to actually control the robot (button mappings and such)
- port numbers (pretty much done)
- any current bugs
- features that plan to be implemented

**Comment by OmariM** [comment]
@juliestreet

double check port numbers from robotmap and webdashbaord (i just wanna be absolutely sure that everything is right)

current bugs: 
- Velocity Control for shooter needs to be tested
- Trajectory mapping doesn't work as intended
- Velocity Control for talons needs to be more carefully tuned so motion profiling can be accurate

upcoming features:
- velocity control on feeder
- jam sensing on carousel
- semi auto and full auto firing capabilities

**Comment by juliestreet** [comment]
Bugs and features added (Will upload as soon as imgur stops pooping itself). Port numbers from robotmap match up but I have not checked webdashboard yet

**Comment by OmariM** [comment]
Dalton update:

Control Scheme:
- operator
-- hold button 3: hanger
-- hold button 6: open gear manipulator

- driver
-- joysticks: arcade drive
-- hold right bumper: extend intake

port updates:
- removed gear pusher solenoids
- double solenoids used for intake and gear manipulator flap (just check robot map)

functionality updates:
- climber, shooter, feeder no longer (remove all documentation for functionality)

known bugs: 
- remove all

future implements:
- remove all
- add side gear auto
