### ISSUE TITLE
Shooter Fixes

### ISSUE THREAD

**Issue by OmariM** [WiredCatsRobotics2415/WiredCats2017#8]
As per Sean and Hailey's request, we don't need a velocity PID for the shooter--just simple bang bang control. This just means that you'll have to scrap the PIDSubsystem for the shooter and just make a regular one that can set (in percent vbus) and get the shooter talon's speed. The shooter command is gonna be a bit different too, still quite simple though. It'll be run on a while held (make it the trigger on the joystick--should be button 1) and if the speed goes over a set rpm, cut power to the motor; otherwise, send 0.420 to the motor.

**Comment by NathanZhu9** [comment]
Re-open if there's something wrong with my code
