### ISSUE TITLE
Feeder Fixes

### ISSUE THREAD

**Issue by OmariM** [WiredCatsRobotics2415/WiredCats2017#9]
As per Sean and Hailey's request, we don't need a velocity PID for the feeder--just simple bang bang control. This just means that you'll have to scrap the PIDSubsystem for the feeder and just make a regular one that can set (in percent vbus) and get the feeder talon's speed. The feeder command is gonna be a bit different too, still quite simple though. It'll be run on a while held (make it the trigger on the joystick--should be button 1) and if the speed goes over a set rpm, cut power to the motor; otherwise, send 0.420 to the motor.

**Comment by isabellapu** [comment]
in the code it's already set to left bumper so I left it since shooter is trigger

**Comment by OmariM** [comment]
yeah u right
